GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "First Blog",
    "author": "Simran Ganju",
    "url": "https://github.com/ganjusimran-dev-diary"
}
